use super::ModelInfo;

/// Curated list of popular open models for the Catalog view.
/// All specs sourced from each model's config.json. All at 4-bit quantization.
pub fn catalog_models() -> Vec<ModelInfo> {
    vec![
        // --- Entry-level ---
        ModelInfo {
            name: "Llama-3.1-8B-4bit".into(),
            path: String::new(),
            model_type: "LlamaForCausalLM".into(),
            architecture: "LlamaForCausalLM".into(),
            hidden_size: 4096,
            num_hidden_layers: 32,
            num_attention_heads: 32,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 4_500_000_000,  // ~4.5 GB at 4-bit
            total_parameters: 8_030_000_000,
            is_moe: false,
        },

        // --- Small/Medium Dense ---
        ModelInfo {
            name: "Phi-4-14B-4bit".into(),
            path: String::new(),
            model_type: "PhiForCausalLM".into(),
            architecture: "PhiForCausalLM".into(),
            hidden_size: 5120,
            num_hidden_layers: 40,
            num_attention_heads: 40,
            num_key_value_heads: 10,
            head_dim: 128,
            max_position_embeddings: 16384,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 8_100_000_000,
            total_parameters: 14_000_000_000,
            is_moe: false,
        },

        ModelInfo {
            name: "Mistral-Small-24B-4bit".into(),
            path: String::new(),
            model_type: "MistralForCausalLM".into(),
            architecture: "MistralForCausalLM".into(),
            hidden_size: 5120,
            num_hidden_layers: 56,
            num_attention_heads: 32,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 32768,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 13_500_000_000,
            total_parameters: 24_000_000_000,
            is_moe: false,
        },

        ModelInfo {
            name: "Gemma-3-27B-4bit".into(),
            path: String::new(),
            model_type: "Gemma3ForCausalLM".into(),
            architecture: "Gemma3ForCausalLM".into(),
            hidden_size: 4608,
            num_hidden_layers: 62,
            num_attention_heads: 32,
            num_key_value_heads: 16,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 15_200_000_000,
            total_parameters: 27_000_000_000,
            is_moe: false,
        },

        // --- MoE (efficient) ---
        ModelInfo {
            name: "Qwen3-30B-A3B-4bit".into(),
            path: String::new(),
            model_type: "Qwen3MoeForCausalLM".into(),
            architecture: "Qwen3MoeForCausalLM".into(),
            hidden_size: 2048,
            num_hidden_layers: 48,
            num_attention_heads: 32,
            num_key_value_heads: 4,
            head_dim: 64,
            max_position_embeddings: 131072,
            num_experts: 128,
            num_experts_per_tok: 8,
            moe_intermediate_size: 1024,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 16_700_000_000,
            total_parameters: 30_500_000_000,
            is_moe: true,
        },

        // --- Medium Dense ---
        ModelInfo {
            name: "Qwen2.5-Coder-32B-4bit".into(),
            path: String::new(),
            model_type: "Qwen2ForCausalLM".into(),
            architecture: "Qwen2ForCausalLM".into(),
            hidden_size: 5120,
            num_hidden_layers: 64,
            num_attention_heads: 40,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 18_500_000_000,
            total_parameters: 32_500_000_000,
            is_moe: false,
        },

        ModelInfo {
            name: "Command-R-35B-4bit".into(),
            path: String::new(),
            model_type: "CohereForCausalLM".into(),
            architecture: "CohereForCausalLM".into(),
            hidden_size: 8192,
            num_hidden_layers: 40,
            num_attention_heads: 64,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 19_800_000_000,
            total_parameters: 35_000_000_000,
            is_moe: false,
        },

        // --- Large Dense ---
        ModelInfo {
            name: "Llama-3.1-70B-4bit".into(),
            path: String::new(),
            model_type: "LlamaForCausalLM".into(),
            architecture: "LlamaForCausalLM".into(),
            hidden_size: 8192,
            num_hidden_layers: 80,
            num_attention_heads: 64,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 39_500_000_000,
            total_parameters: 70_600_000_000,
            is_moe: false,
        },

        ModelInfo {
            name: "Llama-3.3-70B-4bit".into(),
            path: String::new(),
            model_type: "LlamaForCausalLM".into(),
            architecture: "LlamaForCausalLM".into(),
            hidden_size: 8192,
            num_hidden_layers: 80,
            num_attention_heads: 64,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 39_500_000_000,
            total_parameters: 70_600_000_000,
            is_moe: false,
        },

        ModelInfo {
            name: "Qwen2.5-72B-4bit".into(),
            path: String::new(),
            model_type: "Qwen2ForCausalLM".into(),
            architecture: "Qwen2ForCausalLM".into(),
            hidden_size: 8192,
            num_hidden_layers: 80,
            num_attention_heads: 64,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 0,
            num_experts_per_tok: 0,
            moe_intermediate_size: 0,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 40_500_000_000,
            total_parameters: 72_000_000_000,
            is_moe: false,
        },

        // --- Large MoE ---
        ModelInfo {
            name: "Mixtral-8x22B-4bit".into(),
            path: String::new(),
            model_type: "MixtralForCausalLM".into(),
            architecture: "MixtralForCausalLM".into(),
            hidden_size: 6144,
            num_hidden_layers: 56,
            num_attention_heads: 48,
            num_key_value_heads: 8,
            head_dim: 128,
            max_position_embeddings: 65536,
            num_experts: 8,
            num_experts_per_tok: 2,
            moe_intermediate_size: 16384,
            v_head_dim: None,
            qk_nope_head_dim: None,
            qk_rope_head_dim: None,
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 79_000_000_000,
            total_parameters: 140_600_000_000,
            is_moe: true,
        },

        // --- Massive MoE ---
        ModelInfo {
            name: "DeepSeek-V3-0324-4bit".into(),
            path: String::new(),
            model_type: "DeepseekV3ForCausalLM".into(),
            architecture: "DeepseekV3ForCausalLM".into(),
            hidden_size: 7168,
            num_hidden_layers: 61,
            num_attention_heads: 128,
            num_key_value_heads: 128,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 256,
            num_experts_per_tok: 8,
            moe_intermediate_size: 2048,
            v_head_dim: Some(128),
            qk_nope_head_dim: Some(128),
            qk_rope_head_dim: Some(64),
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 377_000_000_000,
            total_parameters: 685_000_000_000,
            is_moe: true,
        },

        ModelInfo {
            name: "DeepSeek-R1-4bit".into(),
            path: String::new(),
            model_type: "DeepseekV3ForCausalLM".into(),
            architecture: "DeepseekV3ForCausalLM".into(),
            hidden_size: 7168,
            num_hidden_layers: 61,
            num_attention_heads: 128,
            num_key_value_heads: 128,
            head_dim: 128,
            max_position_embeddings: 131072,
            num_experts: 256,
            num_experts_per_tok: 8,
            moe_intermediate_size: 2048,
            v_head_dim: Some(128),
            qk_nope_head_dim: Some(128),
            qk_rope_head_dim: Some(64),
            quant_bits: 4,
            quant_group_size: 128,
            total_size_bytes: 377_000_000_000,
            total_parameters: 685_000_000_000,
            is_moe: true,
        },
    ]
}
